[tools]
# Programming Languages & Runtimes
go = "1.24.7"
java = "corretto-17"
node = "latest"
rust = "1.90.0"
scala = "2.13"

# Build Tools and Package Managers
cargo = "latest"
gradle = "8"
maven = "latest"
npm = "latest"
pipx = "latest"
sbt = "latest"
mill = "latest"
coursier = "latest"
pnpm = "latest"

# Infrastructure Tools
argo = "latest"
gh = "latest"
goreleaser = "latest"
helm = "latest"
jj = "latest"
k9s = "latest"
kubectl = "1.32"
kustomize = "latest"
lazydocker = "latest"
lazygit = "latest"
opencode = "latest"
teleport-ent = "16"
terraform = "1.13.4"
tfenv = "latest"

# Linters & Formatters
golangci-lint = "latest"
terraform-docs = "latest"
tflint = "latest"
trivy = "latest"
yamllint = "latest"

# Databases
mysql = "8"

# AI Tools
claude = "latest"
